### ISSUE TITLE
Small differences between devices

### ISSUE THREAD

**Issue by kaweksl** [free-pdk/pdk-includes#1]
How we should deal with small differences between devices , or in another words difference between default periph/xxx and device ?
For example minus input of comparator, on PFS154 GPCC[3-1] '101' is PB7 but on PMS150C is PA7 . by default we have GPCC_COMP_MINUS_PB7 but on PMS150C should be GPCC_COMP_MINUS_PA7 for same value

Create another version of comparator.h ?
add overrides inside device/xxx.h
or maybe create another .h with overrides form default like

override_PMS150C.h
```
#undef GPCC_COMP_MINUS_PB7
#define GPCC_COMP_MINUS_PA7          (5 << GPCC_COMP_MINUS_BIT0)
```

**Comment by kaweksl** [comment]
I think best would be to treat periph as defaults (common) and inside device/xxx.h create overrides.

**Comment by kaweksl** [comment]
Above example can be solved in another way since from what i can tell uC variants without port B have comparator input on PA6,PA7 and those with port B have it on PB6, PB7 so HAS_PORTB could be used inside comparator.h .

But question how we should deal with differences remains.

**Comment by serisman** [comment]
Good catch.  I missed that one from earlier.

This changeset should fix that: https://github.com/free-pdk/pdk-includes/commit/73531185ed4c0be98b691cdc8904284418fa09c5

**Comment by serisman** [comment]
Have you found any other unaccounted for differences yet?

**Comment by kaweksl** [comment]
there are no defines for PADIE/PBDIE values like #define PADIE_PA0_WAKEUP_ENABLE      0x01

**Comment by serisman** [comment]
> there are no defines for PADIE/PBDIE values like #define PADIE_PA0_WAKEUP_ENABLE 0x01

Yeah, those didn't really seem all that useful, because PADIER/PBDIER works the same way as PA/PB, PAC/PBC, PAPH/PBPH, and so on.  Meaning, PxDIER bit 0 is always tied to pin Px.0 and so on and a 0 always means disable and 1 means enable.

I think the only reason they are broken out in the datasheet is because sometimes some of the pins can't be used for interrupt requests, even though they can still be used for digital inputs / wakeup events.

**Comment by kaweksl** [comment]
Yea , past names are also little confusing, maybe add 
```
#define PIN0	0x01
#define PIN1	0x02
#define PIN2	0x04
#define PIN3	0x08
#define PIN4	0x10
#define PIN5	0x20
#define PIN6	0x40
#define PIN7	0x80
```
So we could for example use:
`PADIE = PIN0 | PIN4`

**Comment by serisman** [comment]
Sure, that sounds reasonable to me.  Just have to think of which file that should go in.  Maybe the port_a.h file, because so far every device has a port a.

Here you go: https://github.com/free-pdk/pdk-includes/commit/2a273bb8203c82baf799b3de945245b842cd7352

**Comment by serisman** [comment]
Just added support for PMS154B and PMS154C, and other than catching one more bug (with PWMG2C), I didn't see any new differences that weren't already accounted for.

**Comment by serisman** [comment]
Just added support for PMS131, which was a little different compared to others, but still pretty manageable.  Had to #undef a few things.

https://github.com/free-pdk/pdk-includes/commit/c745d11b74d9d26a1b836e2606981cfc3402a74d

**Comment by serisman** [comment]
Do you still need this issue open?

**Comment by kaweksl** [comment]
Issue solved
