### ISSUE TITLE
HAS_* macro names

### ISSUE THREAD

**Issue by spth** [free-pdk/pdk-includes#2]
I think the HAS_* macro names have a high risk of conflicting with user names (one can easily imagine a programmer choosing HAS_COMP or HAS_ADC for a macro referring to some feature in their software).
Maybe some kind of prefix  could help?

**Comment by serisman** [comment]
Makes sense.

I just added a __PDK_ prefix, so HAS_ADC is now __PDK_HAS_ADC.

Does that work?

**Comment by serisman** [comment]
Fixed with: https://github.com/free-pdk/pdk-includes/commit/4a792b61cc48910d3ba1b53779f4a7818ff0eb6a
and: https://github.com/free-pdk/pdk-includes/commit/79d0ed85e42d46384bf5a1943d3d7d3f33909242
