### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by serisman** [free-pdk/pdk-includes#5]
This repo need a clearly identified LICENSE so people know what can and cannot be done with it.

@freepdk, my preference for this is MIT, but these files have their roots from easy-pdk-programmer-software (even though they have been changed dramatically from what was/is there) which is GPL v3.  Are you ok with (re-)licensing these include files as MIT?

**Comment by serisman** [comment]
Pull Request to add Copyright and License information: https://github.com/free-pdk/pdk-includes/pull/6

**Comment by freepdk** [comment]
SDCC suggested GPL + LinkExcpetion. LGPL is a bit different.

**Comment by serisman** [comment]
> SDCC suggested GPL + LinkExcpetion. LGPL is a bit different.

Yeah, I couldn't really find that as an 'official' license.  Do you have a link that shows that as being a real thing?

I couldn't find it on http://www.gnu.org/licenses, and it isn't directly listed on their exceptions page either: https://www.gnu.org/licenses/exceptions.html

GitHub doesn't know about it: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

SPDX doesn't directly list it (unless it is one of the deprecated ones): https://spdx.org/licenses/

Wikipedia isn't really all that clear, although they do list LGPL as being related: https://en.wikipedia.org/wiki/GPL_linking_exception

Or, do we just list this as GPL 2.0 and include our own exception text (similar to what SDCC uses)? That feels a bit dirty to not use an 'official' license, but maybe it is ok?

**Comment by serisman** [comment]
Ok, here is a different PR with GPL v2 with Linking Exception: https://github.com/free-pdk/pdk-includes/pull/7

**Comment by spth** [comment]
For more details on a GPL+LE, see e.g.:

https://www.gnu.org/licenses/gcc-exception-3.1.en.html

**Comment by serisman** [comment]
Copyright and LICENSE information was merged via Pull Request #7
